export const CREATE_NOTE = 'NOTE/CREATE_NOTE',
  CLOSE_NOTE = 'NOTE/CLOSE_NOTE',
  SAVE_NOTE = 'NOTE/SAVE_NOTE',
  DELETE_NOTE = 'NOTE/DELETE_NOTE',
  SELECT_NOTE = 'NOTE/SELECT_NOTE',
  SET_USED_NOTE = 'NOTE/SET_USED_NOTE'
