export const CHANGE_USED_NOTE = 'CHANGE_USED_NOTE',
  GET_SELECT_NOTE = 'GET_SELECT_NOTE',
  CLOSE_NOTE = 'CLOSE_NOTE',
  SAVE_NOTE = 'SAVE_NOTE',
  DELETE_NOTE = 'DELETE_NOTE',
  CREATE_NOTE = 'CREATE_NOTE',
  GET_TEXT_LENGTH = 'GET_TEXT_LENGTH',
  NOTE_SORT = 'NOTE_SORT'
